spring.application.name=taskmanagement

spring.datasource.url=jdbc:mariadb://localhost:3306/taskManagement
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123

jwt.secret = ThisApplacationSecretIsUnickWithThisSecretCode123456789@
jwt.expiration = 1200000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
server.error.include-message=always